export default {
    ASYNC_FETCH_ALL_VODS : 'ASYNC_FETCH_ALL_VODS',
    FETCH_SUCCESS_ALL_VODS : 'FETCH_SUCCESS_ALL_VODS',
    FETCH_FAILD_ALL_VODS: 'FETCH_FAILD_ALL_VODS',
    ASYNC_FETCH_CATEGORY_VODS: 'ASYNC_FETCH_CATEGORY_VODS',
    FETCH_SUCCESS_CATEGORY_VODS: 'FETCH_SUCCESS_CATEGORY_VODS', 
    FETCH_FAILD_CATEGORY_VODS : 'FETCH_FAILD_CATEGORY_VODS',
}